<?php

define('CONF_DATABASE_DRIVER',$_ENV['DBDRIVER']);
define('CONF_DATABASE_HOST',$_ENV['DBHOST']);
define('CONF_DATABASE_NAME',$_ENV['DBNAME']);
define('CONF_DATABASE_USER',$_ENV['DBUSER']);
define('CONF_DATABASE_PASS',$_ENV['DBPASS']);
define('CONF_DATABASE_OPTIONS',[
    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,# Feedback de erros.
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ,
    PDO::ATTR_CASE => PDO::CASE_NATURAL# Conversão de nome de colunas.
]);
